
  package org.ivoa.vodml.stdtypes2;

    
    
        
       import javax.persistence.*;
    
/**
* An integer number with a unit. Examples of such units that can be used for attributes are bit/byte/kiloByte etc.
*
* dataType:  IntegerQuantity
*
* @author generated by https://github.com/ivoa/vo-dml tools
*/
    @Embeddable


  @javax.xml.bind.annotation.XmlAccessorType( javax.xml.bind.annotation.XmlAccessType.NONE )  
  @javax.xml.bind.annotation.XmlType( name = "IntegerQuantity")
    
 @org.ivoa.vodml.annotation.VoDml(ref="ivoa:IntegerQuantity", type=org.ivoa.vodml.annotation.VodmlType.dataType)
 
       public  class IntegerQuantity extends Quantity {
      
    /** 
    * The integer value of this IntegerQuantity. : Attribute value : multiplicity 1
    *
    */
    
 @org.ivoa.vodml.annotation.VoDml(ref="ivoa:IntegerQuantity.value", type=org.ivoa.vodml.annotation.VodmlType.attribute)
 
        @Basic( optional = true ) // IMPL have changed the nullability to allow cases where it is embedded to be null - cannot override this easily in hibernate
        @Column( name = "value", nullable = false )
                            
    @javax.xml.bind.annotation.XmlElement( name = "value", required = true, type = Integer.class)
    
    protected Integer value;
        
      /**
       * Creates a new IntegerQuantity
       */
      public IntegerQuantity() {
        super();
      }
      
        /**
        * full parameter constructor.
        */
        public  IntegerQuantity (
          final Integer value, final org.ivoa.vodml.stdtypes2.Unit unit
        )
        {
           
           this.value = value;
           
           this.unit = unit;
           
        }
        
        /**
        * Returns value Attribute
        * @return value Attribute
        */
        
        public Integer getValue() {
        return (Integer)this.value;
        }
        
        
        /**
        * Defines value Attribute
        * @param pValue value to set
        */
        public void setValue(final Integer pValue) {
        this.value = pValue;
        }
        

        public IntegerQuantity withValue(final Integer pValue) {
        this.value = pValue;
        return this;
        }

    
        /**
          A builder class for IntegerQuantity principally to be used in the functional builder pattern.
        */
        public static class IntegerQuantityBuilder {
           
           /**
           * The integer value of this IntegerQuantity.
           */
           public Integer value;
                   
           /**
           * The unit of this  quantity.
           */
           public org.ivoa.vodml.stdtypes2.Unit unit;
                   

           private IntegerQuantityBuilder with (java.util.function.Consumer <IntegerQuantityBuilder> f)
           {
             f.accept(this);
             return this;
           }
           /**
             create a IntegerQuantity from this builder.
           */
           public IntegerQuantity create()
           {
             return new IntegerQuantity (
             value,unit
             );
           }
         }
         /**
           create a IntegerQuantity in functional builder style.
         */
         public static IntegerQuantity createIntegerQuantity (java.util.function.Consumer <IntegerQuantityBuilder> f)
         {
             return new IntegerQuantityBuilder().with(f).create();
         }
    



}
  