name: site
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: 'pip'
      - run: pip install mkdocs-material==9.5.25

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Setup Dependencies
        run: |
          sudo apt update
          sudo apt install graphviz
          sudo snap install yq 


      - name: Deploy site
        run: |
          ./gradlew doSite
