
name: Run ProposalDM tests

env:
  doc_name: ProposalDM

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout the repository
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'


    - name: Run the tests
      run: |
         ./gradlew test

